// <auto-generated />
using Just_project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Just_project.Migrations
{
    [DbContext(typeof(LocalizeDbContext))]
    partial class LocalizeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Just_project.Models.LocalizedString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LocalizedStrings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "ProductDescription",
                            Language = "en-US",
                            Value = "Gaming PC"
                        },
                        new
                        {
                            Id = 2,
                            Key = "ProductDescription",
                            Language = "ru-RU",
                            Value = "Игровой ПК"
                        },
                        new
                        {
                            Id = 3,
                            Key = "ProductDescription",
                            Language = "kk-KZ",
                            Value = "Ойын компьютері"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
